<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.quipux</groupId>
        <artifactId>api-canciones</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>h2-adapter</artifactId>
    <packaging>jar</packaging>
    <name>h2-adapter</name>

    <dependencies>
        <dependency>
            <groupId>com.quipux</groupId>
            <artifactId>use-cases</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.quipux</groupId>
            <artifactId>models</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
        <!-- Dependencia para JPA si accedes a DB desde aquí -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
    </dependencies>
</project>